name: "Rerun Workflow"
description: "Rerun Workflow"

inputs:
  action-token:
    description: "GitHub token for access GitHub repository"
    required: true
  user:
    description: "The user which corresponding to action-token"
    required: true
  workflow-this:
    description: "The name which corresponding this action"
    required: true

runs:
  using: "node16"
  main: "src/index.js"
branding:
  icon: "tag"
  color: "blue"
